/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS
 * Placeholder untuk migration ke Laravel. Isi asli (Supabase anon key) diganti
 * agar tidak ter-commit ke repo. Frontend sebenarnya tidak lagi butuh Supabase
 * (lihat docs/ARCHITECTURE.md — backend Laravel + Cloudinary).
 */

export const projectId = "REPLACE_WITH_SUPABASE_PROJECT_REF";
export const publicAnonKey = "REPLACE_WITH_SUPABASE_ANON_KEY";
